feat: 카카오 로그인, 인증, 인가 처리
team-comma/hmm-backend-v2 pull request #2
Opened 2022-12-20 12:33 UTC by daeuk4371

## 🔍 What is this PR?
로그인, 인증, 인가 처리 기능 추가

## 🙇 Changes

- 로그인 기능 추가
- 로그아웃 기능 추가
- 리프레시 토큰 캐시에 저장
- 공통 응답 세팅
- swagger 문서화 설정

## 📸 스크린 샷

**어떤 점이 달라졌는지 알 수 있게끔 스크린 샷을 첨부해주세요.**

## ✅ 체크 리스트

- [ ] **테스트 계획 또는 완료된 사항의 체크리스트를 작성해주세요.**

2022-12-21 14:40 UTC, HanSeo0507 requested changes

2022-12-21 14:40 UTC, HanSeo0507 commented on src/auth/auth.service.ts
> +      console.log(error);
디버깅 코드 제거해주세요 :)

2022-12-22 08:22 UTC, cmg8431 commented on src/auth/auth.service.ts
> +  private async login(member: Member, ip: string, res: Response) {
@daeuk4371 
이 부분은 궁금해서 코맨트 남깁니다! 프론트엔드에서는 보통 props가 많아질 경우 Interface나 type을 따로 선언 후 처리하는 데 백엔드에서는 해당 타입 명시를 본 적이 굉장히 적은 것 같습니다! 혹시 사용하지않는 이유가 따로 있을까요?

2022-12-22 08:49 UTC, cmg8431 commented on src/auth/auth.controller.ts
>    @Get('/login/oauth/kakao')
@daeuk4371 
해당 요청 주소같은 부분들은 constants같은 폴더가 있다면 해당 폴더에서 전역적으로 관리하는게 어떨까요? 해당 부분은 프론트엔드 기준이므로 대욱님이 판단 후 적용시켜주셨으면 좋겠습니다!

2022-12-22 09:02 UTC, cmg8431 commented on src/auth/strategies/kakao.strategy.ts
> +import { MemberKakaoDto } from '../dto';
@daeuk4371 
nest.js에서는 절대경로 설정이 불가능 할까요? 가능하면 적용하는 게 좋을 듯 싶습니다!

2022-12-22 09:02 UTC, cmg8431 commented on src/auth/strategies/kakao.strategy.ts
> +  async validate(accessToken: string, refreshToken: string, profile: Profile, done: any) {
@daeuk4371 
done의 타입이 any인데 해당 부분은 타입 명시가 어려울까요?

2022-12-22 09:02 UTC, cmg8431 commented on package.json
>    "dependencies": {
@daeuk4371 
일반 디펜던시와 디벨롭 디펜던시의 구분이 확실한지 한번 확인 부탁드릴게요!

2022-12-22 09:02 UTC, cmg8431 commented on src/app.module.ts
>            logging: configService.get<string>('DB_LOGGING') === 'true',
@daeuk4371
해당 부분은 원래 `true`가 아닌 `'true'`로 비교하는게 맞을까요?

2022-12-22 09:07 UTC, HanSeo0507 commented on src/auth/auth.controller.ts
>    @Get('/login/oauth/kakao')
컨트롤러 요청 주소는 대욱님이 작성하신 방식이 저는 괜찮지 않을까 싶네요 :)
NestJS에서 제공해주는 예제들 참고해봐도 저희가 프론트에서 관리하는 방식처럼 제공되는 예제는 없기도 했고, 지금 상태로도 딱히 관리적인 부분에선 별 차이가 없을 것 같아요 !

2022-12-22 09:17 UTC, cmg8431 commented on src/auth/auth.controller.ts
>    @Get('/login/oauth/kakao')
https://github.com/team-codedc/kap-frontend/blob/master/src/constant/screen.ts

해당 코드에서 나오는 부분과 유사하다고 생각해서 공유해보았는데 확실히 큰 차이는 없을 듯 해서 백엔드 팀원 분들이 판단 후 편한대로 가는게 맞는 것 같네요! 감사합니다 :)

2022-12-22 09:21 UTC, HanSeo0507 requested changes
지금 당장은 테스트 코드 작성은 안하시는 것 같은데, 그러면 컨트롤러, 서비스 생성 시 자동으로 생성되는 NestJS 기본 테스트 코드는 삭제하는 건 어떨까요?

2022-12-22 09:21 UTC, HanSeo0507 commented on src/auth/auth.controller.ts
> +    return this.authService.register(req.user as MemberKakaoDto, ip, res);
`as` 문법은 별로 TypeSafe하지 않은 방법인 거 같아요.
`Express.User`를 전역으로 타입 지정해주는 건 어떨까요?

2022-12-22 09:21 UTC, HanSeo0507 commented on src/auth/auth.controller.ts
> +    return this.authService.register(req.user as MemberKakaoDto, ip, res);
21번, 27번 줄도 같이 확인해주세요 :)

2022-12-22 09:21 UTC, HanSeo0507 commented on src/auth/auth.service.ts
> +  private async login(member: Member, ip: string, res: Response) {
저도 이 부분은 궁금하네요.
물론 정답은 없지만, 저 같은 경우는 대부분 DTO를 사용해서 아래 코드와 같이 작성하는 방식을 많이 사용했는데, 일일이 매개변수를 지정하시는 이유가 있을까요?

```ts
interface LoginDTO {
  member: Member;
  ip: string;
  res: Response;
}

class AuthService {
  private async login({ member, ip, res }: LoginDTO) {
    // login logics
  }
}
```

2022-12-22 09:21 UTC, HanSeo0507 commented on src/auth/strategies/kakao.strategy.ts
> +import { MemberKakaoDto } from '../dto';
이 부분은 저도 동감합니다 :)
절대경로 도입하는 게 좋을 것 같네요

2022-12-22 09:50 UTC, daeuk4371 commented on src/app.module.ts
>            logging: configService.get<string>('DB_LOGGING') === 'true',
string으로 받아서 'true'로 비교하는 것이 맞습니다!

2022-12-22 09:57 UTC, daeuk4371 commented on package.json
>    "dependencies": {
이 부분은 잘못됬네요. 분리하겠습니다!

2022-12-24 07:25 UTC, daeuk1011 commented on src/auth/auth.service.ts
> +  private async login(member: Member, ip: string, res: Response) {
전 개인적으로 굳이 nest, express 공식적인 라이브러리에서 가져오는 것을 dto로 선언을 해야 하나 싶습니다. 그래서 저는 body에서 받아오는 것들만 주로 dto를 사용해서 작성합니다. (swagger 문서화 부분도 있음)

2022-12-24 07:25 UTC, daeuk1011 commented on src/auth/strategies/kakao.strategy.ts
> +import { MemberKakaoDto } from '../dto';
절대 경로로 바꾸겠습니다.

2022-12-24 07:40 UTC, cmg8431 approved these changes
LGTM

2022-12-24 13:12 UTC, merged